name: places
description: A new Flutter project 'Places' by Maxim Konstantinov.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dart_code_metrics: ^4.13.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  surf_lint_rules: ^1.5.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - res/images/
    - res/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: res/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: res/fonts/Roboto-Bold.ttf
          weight: 700
